language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

php:
 - 5.6
 - 7.0

env:
 matrix:
  - DB=pgsql MOODLE_BRANCH=MOODLE_30_STABLE
  - DB=pgsql MOODLE_BRANCH=master


before_install:
    # Save the xdebug config for later use.
  - cp ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini ~/
  - phpenv config-rm xdebug.ini
  - cd ../..
  - composer selfupdate
  - composer create-project -n --no-dev moodlerooms/moodle-plugin-ci ci ^1
  - composer require satooshi/php-coveralls
  - export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"

install:
  - moodle-plugin-ci install

script:
    # Make a dir for the logs.
  - mkdir -p moodle/local/coverage/build/logs
    # Add logging and whitelist to the phpunit file.
  - export XML="<logging><log type=\"coverage-clover\" target=\"$(pwd)/moodle/local/coverage/build/logs/clover.xml\"/></logging>"
  - export XMLINCLUDE="<directory suffix=\".php\">local/coverage</directory>"
  - export XMLEXCLUDE="<directory suffix=\".php\">local/coverage/lang</directory><file>local/coverage/version.php</file>"
  - export XML="$XML<filter><whitelist addUncoveredFilesFromWhitelist=\"true\" processUncoveredFilesFromWhitelist=\"false\">$XMLINCLUDE<exclude>$XMLEXCLUDE</exclude></whitelist></filter>"
  - sed "/<testsuites>/  s|<testsuites>|$XML<testsuites>| " moodle/phpunit.xml > moodle/phpunit2.xml
    # Re-add xdebug for phpunit coverage tracking.
  - phpenv config-add ~/xdebug.ini
  - moodle-plugin-ci phpunit
  
after_success:
    # Create a coveralls file in the plugin dir, otherwise php-coveralls will get confused.
  - echo "coverage_clover: $(pwd)/build/logs/clover.xml" > moodle/local/coverage/.coveralls.yml
  - echo "json_path: $(pwd)/build/logs/coveralls-upload.json" >> moodle/local/coverage/.coveralls.yml
    # Need to move into the plugin dir to run, because it uses the git info.
  - cd moodle/local/coverage
  - travis_retry php ../../../coveralls/bin/coveralls -v

